[env:arduino_nano_esp32]
platform = espressif32
board = arduino_nano_esp32
framework = arduino

monitor_speed = 115200
monitor_filters = direct

upload_protocol = espota
upload_port = 192.168.50.69

build_flags =
    -std=gnu++17